### ISSUE TITLE
Config option or feature to prevent players from using flint & steel to light portals.

### ISSUE THREAD

**Issue by JENOVAAbsolute** [Insane-96/NaturalNetherPortalsMod#9]
Can you add an option to prevent players from lighting portals with flint & steel? Specifically for those people who have other methods of entering the nether, such as this mod spawning only lit portals, or for people who use Unforgiving Void, which let's them enter the nether by falling into the void. I tried using this mod together with both No Nether Portals, and Pam's Portal Poof, which "prevent the creation of portals". Neither of these mods work (At least on my modpack, but I have no mods that alter the nether dimension, obsidian, or flint & steel). Not only do they not prevent portals from being made as intended, but even if your mod is configured to ONLY spawn lit portals, both those mods prevent naturally spawned ones from this mod to spawn lit.

**Comment by Insane96** [comment]
Not the objective of the mod
